name: MGM240P OpenThread RCP
device: MGM240PB32VNA
base_project: src/openthread_rcp
filename: "{manifest_name}_{ot_version}_{baudrate}_{fw_variant}"
sdk: "simplicity_sdk:2024.6.2"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: openthread_rcp
  ot_version: dynamic
  baudrate: 460800
  fw_variant: no_flow

c_defines:
  SL_UARTDRV_USART_VCOM_FLOW_CONTROL_TYPE: usartHwFlowControlNone

  SL_UARTDRV_USART_VCOM_PERIPHERAL: USART0
  SL_UARTDRV_USART_VCOM_PERIPHERAL_NO: 0
  SL_UARTDRV_USART_VCOM_BAUDRATE: 460800

  SL_UARTDRV_USART_VCOM_TX_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_TX_PIN:  5

  SL_UARTDRV_USART_VCOM_RX_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_RX_PIN:  6

  SL_UARTDRV_USART_VCOM_CTS_PORT: 0
  SL_UARTDRV_USART_VCOM_CTS_PIN:  0

  SL_UARTDRV_USART_VCOM_RTS_PORT: 0
  SL_UARTDRV_USART_VCOM_RTS_PIN:  0

  SL_CLOCK_MANAGER_HFXO_EN: 1
  SL_CLOCK_MANAGER_HFXO_CTUNE: 140

  SL_RAIL_UTIL_RSSI_OFFSET: 0
