name: Yellow Multi-PAN
device: MGM210PA32JIA
base_project: rcp-uart-802154

gbl:
  fw_type: rcp-uart-802154
  dynamic: ["ezsp_version", "otbr_version", "cpc_version"]
  baudrate: 460800

add_components:
- id: simple_led
  instance: [board_activity]

configuration:
  SL_RAIL_UTIL_PTI_MODE: RAIL_PTI_MODE_DISABLED
  SL_CPC_DRV_UART_VCOM_BAUDRATE: 460800

c_defines:
  CPC_SECONDARY_APP_VERSION_SUFFIX: '"-{git_repo_hash}"'

  SL_CPC_DRV_UART_VCOM_PERIPHERAL: USART0
  SL_CPC_DRV_UART_VCOM_PERIPHERAL_NO: 0

  SL_CPC_DRV_UART_VCOM_TX_PORT: gpioPortA
  SL_CPC_DRV_UART_VCOM_TX_PIN:  5

  SL_CPC_DRV_UART_VCOM_RX_PORT: gpioPortA
  SL_CPC_DRV_UART_VCOM_RX_PIN:  6

  SL_CPC_DRV_UART_VCOM_CTS_PORT: gpioPortD
  SL_CPC_DRV_UART_VCOM_CTS_PIN:  2

  SL_CPC_DRV_UART_VCOM_RTS_PORT: gpioPortC
  SL_CPC_DRV_UART_VCOM_RTS_PIN:  1

  SL_SIMPLE_LED_BOARD_ACTIVITY_POLARITY: SL_SIMPLE_LED_POLARITY_ACTIVE_LOW
  SL_SIMPLE_LED_BOARD_ACTIVITY_PORT:     gpioPortB
  SL_SIMPLE_LED_BOARD_ACTIVITY_PIN:      1
