name: Home Assistant Connect ZBT-2 Bootloader
device: EFR32MG24A420F1536IM40
base_project: src/bootloader
filename: "{manifest_name}_{gecko_bootloader_version}"
sdk: "gecko_sdk:4.5.0"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: gecko-bootloader
  gecko_bootloader_version: dynamic
  baudrate: 115200

sdk_extension:
  - id: bootloader_gpio_activation_dual
    vendor: nabucasa
    version: 1.0.0

remove_components:
  - id: bootloader_gpio_activation

add_components:
  - id: bootloader_gpio_activation_dual

c_defines:
  SL_SERIAL_UART_FLOW_CONTROL: 1

  SL_SERIAL_UART_PERIPHERAL: USART0
  SL_SERIAL_UART_PERIPHERAL_NO: 0

  SL_SERIAL_UART_TX_PORT: gpioPortA
  SL_SERIAL_UART_TX_PIN:  8
  SL_SERIAL_UART_RX_PORT: gpioPortA
  SL_SERIAL_UART_RX_PIN:  7
  SL_SERIAL_UART_CTS_PORT: gpioPortA
  SL_SERIAL_UART_CTS_PIN:  5
  SL_SERIAL_UART_RTS_PORT: gpioPortA
  SL_SERIAL_UART_RTS_PIN:  0

  # The bootloader does not allow downgrades so we need to bump the version
  BOOTLOADER_VERSION_MAIN_CUSTOMER: 4

  # Dual GPIO activation for the bootloader
  # Triggered by trace to S3
  NC_PRIMARY_GPIO_ACTIVATION_POLARITY: LOW
  NC_BTL_BUTTON_PRIMARY_PORT: gpioPortA
  NC_BTL_BUTTON_PRIMARY_PIN: 6

  # And by the reset button on the back
  NC_SECONDARY_GPIO_ACTIVATION_POLARITY: LOW
  NC_BTL_BUTTON_SECONDARY_PORT: gpioPortC
  NC_BTL_BUTTON_SECONDARY_PIN: 5