name: SkyConnect OpenThread RCP
device: EFR32MG21A020F512IM32
base_project: src/openthread_rcp
filename: "{manifest_name}_{ot_rcp_version.split('/')[-1]}_gsdk_{sdk_version}"
sdk: "gecko_sdk:4.4.4"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: openthread_rcp
  ot_rcp_version: dynamic
  baudrate: 460800

c_defines:
  SL_UARTDRV_USART_VCOM_PERIPHERAL: USART0
  SL_UARTDRV_USART_VCOM_PERIPHERAL_NO: 0
  SL_UARTDRV_USART_VCOM_BAUDRATE: 460800

  SL_UARTDRV_USART_VCOM_TX_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_TX_PIN:  6

  SL_UARTDRV_USART_VCOM_RX_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_RX_PIN:  5

  SL_UARTDRV_USART_VCOM_CTS_PORT: gpioPortB
  SL_UARTDRV_USART_VCOM_CTS_PIN:  1

  SL_UARTDRV_USART_VCOM_RTS_PORT: gpioPortB
  SL_UARTDRV_USART_VCOM_RTS_PIN:  0

  SL_APPLICATION_PRODUCT_ID: '{0xE9, 0x92, 0x67, 0x94, 0xBB, 0x2C, 0x4E, 0xC8, 0x9F, 0x36, 0xD9, 0xC6, 0x79, 0x4A, 0x81, 0xFB}'
