name: SkyConnect Bluetooth
device: EFR32MG21A020F512IM32
base_project: src/bt_rcp
filename: "{manifest_name}_{sdk_version}"

gbl:
  fw_type: bt_rcp
  baudrate: 115200

configuration:
  SL_UARTDRV_USART_VCOM_BAUDRATE: 115200
  SL_UARTDRV_USART_VCOM_FLOW_CONTROL_TYPE: usartHwFlowControlCtsAndRts

c_defines:
  SL_UARTDRV_USART_VCOM_PERIPHERAL: USART0
  SL_UARTDRV_USART_VCOM_PERIPHERAL_NO: 0

  SL_UARTDRV_USART_VCOM_TX_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_TX_PIN:  6

  SL_UARTDRV_USART_VCOM_RX_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_RX_PIN:  5

  SL_UARTDRV_USART_VCOM_CTS_PORT: gpioPortB
  SL_UARTDRV_USART_VCOM_CTS_PIN:  1

  SL_UARTDRV_USART_VCOM_RTS_PORT: gpioPortB
  SL_UARTDRV_USART_VCOM_RTS_PIN:  0

  SL_APPLICATION_PRODUCT_ID: '{0xE9, 0x92, 0x67, 0x94, 0xBB, 0x2C, 0x4E, 0xC8, 0x9F, 0x36, 0xD9, 0xC6, 0x79, 0x4A, 0x81, 0xFB}'
