name: Yellow Zigbee
device: MGM210PA32JIA
base_project: src/zigbee_ncp
filename: "{manifest_name}_{ezsp_version}"
sdk: "gecko_sdk:4.5.0"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: zigbee_ncp
  ezsp_version: dynamic
  baudrate: 115200

sdk_extension:
  - id: xncp
    version: 1.0.0
  - id: xncp_common
    version: 1.0.0

add_components:
- id: simple_led
  instance: [board_activity]
- id: xncp_core
  from: xncp
- id: xncp_common_commands
  from: xncp_common

c_defines:
  XNCP_MFG_MANUF_NAME: '"Nabu Casa"'
  XNCP_MFG_BOARD_NAME: '"Home Assistant Yellow"'
  XNCP_BUILD_STRING: template:"{now:%Y%m%d%H%M%S}"
  XNCP_MANUAL_SOURCE_ROUTE_TABLE_SIZE: 200

  EMBER_APS_UNICAST_MESSAGE_COUNT: 32
  EMBER_BINDING_TABLE_SIZE: 32
  EMBER_BROADCAST_TABLE_SIZE: 64
  EMBER_KEY_TABLE_SIZE: 12
  EMBER_MAX_END_DEVICE_CHILDREN: 32
  EMBER_PACKET_BUFFER_COUNT: 255
  EMBER_SOURCE_ROUTE_TABLE_SIZE: 200

  EMBER_CHILD_TABLE_SIZE:
    type: c_flag
    value: 32

  EMBER_ROUTE_TABLE_SIZE:
    type: c_flag
    value: 250

  SL_IOSTREAM_USART_VCOM_BAUDRATE: 115200
  SL_IOSTREAM_USART_VCOM_FLOW_CONTROL_TYPE: usartHwFlowControlCtsAndRts

  SL_IOSTREAM_USART_VCOM_PERIPHERAL: USART0
  SL_IOSTREAM_USART_VCOM_PERIPHERAL_NO: 0

  SL_IOSTREAM_USART_VCOM_TX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_TX_PIN:  5

  SL_IOSTREAM_USART_VCOM_RX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_RX_PIN:  6

  SL_IOSTREAM_USART_VCOM_CTS_PORT: gpioPortD
  SL_IOSTREAM_USART_VCOM_CTS_PIN:  2

  SL_IOSTREAM_USART_VCOM_RTS_PORT: gpioPortC
  SL_IOSTREAM_USART_VCOM_RTS_PIN:  1

  SL_SIMPLE_LED_BOARD_ACTIVITY_POLARITY: SL_SIMPLE_LED_POLARITY_ACTIVE_LOW
  SL_SIMPLE_LED_BOARD_ACTIVITY_PORT:     gpioPortB
  SL_SIMPLE_LED_BOARD_ACTIVITY_PIN:      1
