name: Yellow OpenThread RCP
device: MGM210PA32JIA
base_project: src/openthread_rcp
filename: "{manifest_name}_{ot_rcp_version.split('/')[-1]}_gsdk_{sdk_version}"
sdk: "simplicity_sdk:2025.6.2"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: openthread_rcp
  ot_rcp_version: dynamic
  baudrate: 460800

add_components:
- id: simple_led
  instance: [board_activity]

# SLC validates clock settings before c_defines are patched, use `configuration`
configuration:
  SL_CLOCK_MANAGER_PCLK_DIVIDER: SL_CLOCK_MANAGER_PCLK_DIV_MIN

c_defines:
  # SDK bug: the PCLK divider is set to 1 for the MGM210, it is set to 2 everywhere else
  SL_CLOCK_MANAGER_PCLK_DIVIDER: SL_CLOCK_MANAGER_PCLK_DIV_MIN

  SL_IOSTREAM_USART_VCOM_PERIPHERAL: USART0
  SL_IOSTREAM_USART_VCOM_PERIPHERAL_NO: 0
  SL_IOSTREAM_USART_VCOM_BAUDRATE: 460800
  SL_IOSTREAM_USART_VCOM_TX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_TX_PIN:  5
  SL_IOSTREAM_USART_VCOM_RX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_RX_PIN:  6
  SL_IOSTREAM_USART_VCOM_CTS_PORT: gpioPortD
  SL_IOSTREAM_USART_VCOM_CTS_PIN:  2
  SL_IOSTREAM_USART_VCOM_RTS_PORT: gpioPortC
  SL_IOSTREAM_USART_VCOM_RTS_PIN:  1

  SL_SIMPLE_LED_BOARD_ACTIVITY_POLARITY: SL_SIMPLE_LED_POLARITY_ACTIVE_LOW
  SL_SIMPLE_LED_BOARD_ACTIVITY_PORT:     gpioPortB
  SL_SIMPLE_LED_BOARD_ACTIVITY_PIN:      1
