name: Home Assistant Connect ZBT-2 OpenThread RCP
device: EFR32MG24A420F1536IM40
base_project: src/openthread_rcp
filename: "{manifest_name}_{ot_rcp_version.split('/')[-1]}_gsdk_{sdk_version}"
sdk: "gecko_sdk:4.5.0"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: openthread_rcp
  ot_rcp_version: dynamic
  baudrate: 460800

sdk_extension:
  - id: nabucasa_hardware
    version: 1.0.0
  - id: led_effects_openthread
    version: 1.0.0

add_components:
- id: uartdrv_eusart
  instance: [ws2812_uart]
- id: emlib_i2c
- id: i2cspm
  instance: [inst]
- id: simple_button
  instance: [pin_hole_button]
- id: ws2812_driver
  from: nabucasa_hardware
- id: qma6100p_driver
  from: nabucasa_hardware
- id: led_effects_openthread
  from: led_effects_openthread
- id: zbt2_reset_button
  from: nabucasa_hardware

c_defines:
  SL_DEVICE_INIT_HFXO_FREQ: 39000000
  SL_DEVICE_INIT_HFXO_PRECISION: 10
  SL_DEVICE_INIT_HFXO_CTUNE: 108

  SL_UARTDRV_USART_VCOM_PERIPHERAL: USART0
  SL_UARTDRV_USART_VCOM_PERIPHERAL_NO: 0
  SL_UARTDRV_USART_VCOM_BAUDRATE: 460800

  SL_UARTDRV_USART_VCOM_TX_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_TX_PIN:  8
  SL_UARTDRV_USART_VCOM_RX_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_RX_PIN:  7
  SL_UARTDRV_USART_VCOM_CTS_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_CTS_PIN:  5
  SL_UARTDRV_USART_VCOM_RTS_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_RTS_PIN:  0

  # LED driver
  WS2812_MOSI_PORT: gpioPortC
  WS2812_MOSI_PIN: 2
  WS2812_SCLK_PORT: gpioPortD
  WS2812_SCLK_PIN: 2
  WS2812_EN_PORT: gpioPortC
  WS2812_EN_PIN: 3
  WS2812_EUSART_NUM: 1
  WS2812_LDMA_CHANNEL: 1
  WS2812_NUM_LEDS: 4

  # I2C
  SL_I2CSPM_INST_PERIPHERAL: I2C0
  SL_I2CSPM_INST_SCL_PORT: gpioPortC
  SL_I2CSPM_INST_SCL_PIN: 6
  SL_I2CSPM_INST_SDA_PORT: gpioPortC
  SL_I2CSPM_INST_SDA_PIN: 7

  # Pinhole button
  SL_SIMPLE_BUTTON_PIN_HOLE_BUTTON_PORT: gpioPortC
  SL_SIMPLE_BUTTON_PIN_HOLE_BUTTON_PIN: 5

  # Product ID to prevent cross-flashing across devices
  SL_APPLICATION_PRODUCT_ID: '{0xE9, 0x92, 0x67, 0x94, 0xBB, 0x2C, 0x4E, 0xC8, 0x9F, 0x36, 0xD9, 0xC6, 0x79, 0x4A, 0x81, 0xFB}'
