name: Home Assistant Connect ZBT-2 Zigbee
device: EFR32MG24A420F1536IM40
base_project: src/zigbee_ncp
filename: "{manifest_name}_{ezsp_version}_{fw_variant}"
sdk: "gecko_sdk:4.5.0"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: zigbee_ncp
  fw_variant: "20250911_final"
  ezsp_version: dynamic
  #compression: lzma
  baudrate: 460800

sdk_extension:
  - id: ws2812_driver

add_components:
- id: uartdrv_eusart
  instance: [ws2812_uart]
- id: emlib_i2c
- id: i2cspm
  instance: [inst]
- id: simple_button
  instance: [pin_hole_button]
- id: ws2812_driver

add_sources:
  - path: drivers/qma6100p.c
  - path: drivers/led_effects.c

add_includes:
  - path: drivers
    file_list:
    - path: qma6100p.h
    - path: led_effects.h

c_defines:
  XNCP_MFG_MANUF_NAME: '"Nabu Casa"'
  XNCP_MFG_BOARD_NAME: '"Home Assistant Connect ZBT-2"'
  XNCP_BUILD_STRING: template:"{now:%Y%m%d%H%M%S}"

  # The hardware flow control is only between the S3 and the MG24. The application
  # should not use hardware flow control.
  XNCP_FLOW_CONTROL_TYPE: usartHwFlowControlNone

  EMBER_APS_UNICAST_MESSAGE_COUNT: 32
  EMBER_BINDING_TABLE_SIZE: 32
  EMBER_BROADCAST_TABLE_SIZE: 64
  EMBER_KEY_TABLE_SIZE: 12
  EMBER_MAX_END_DEVICE_CHILDREN: 32
  EMBER_PACKET_BUFFER_COUNT: 255
  EMBER_SOURCE_ROUTE_TABLE_SIZE: 200

  EMBER_CHILD_TABLE_SIZE:
    type: c_flag
    value: 32

  EMBER_ROUTE_TABLE_SIZE:
    type: c_flag
    value: 250

  # To enable/disable blocks of code
  NC_CONNECT_ZBT_2:
    type: c_flag
    value: 1

  SL_DEVICE_INIT_HFXO_FREQ: 39000000
  SL_DEVICE_INIT_HFXO_PRECISION: 10
  SL_DEVICE_INIT_HFXO_CTUNE: 108

  SL_IOSTREAM_USART_VCOM_BAUDRATE: 460800
  SL_IOSTREAM_USART_VCOM_FLOW_CONTROL_TYPE: usartHwFlowControlCtsAndRts

  SL_IOSTREAM_USART_VCOM_PERIPHERAL: USART0
  SL_IOSTREAM_USART_VCOM_PERIPHERAL_NO: 0

  SL_IOSTREAM_USART_VCOM_TX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_TX_PIN:  8
  SL_IOSTREAM_USART_VCOM_RX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_RX_PIN:  7
  SL_IOSTREAM_USART_VCOM_CTS_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_CTS_PIN:  5
  SL_IOSTREAM_USART_VCOM_RTS_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_RTS_PIN:  0

  SL_UARTDRV_EUSART_WS2812_UART_PERIPHERAL:
    type: config
    value: EUSART1
    error_on_duplicate: false

  SL_UARTDRV_EUSART_WS2812_UART_PERIPHERAL_NO:
    type: config
    value: 1
    error_on_duplicate: false

  SL_UARTDRV_EUSART_WS2812_UART_TX_PORT:
    type: config
    value: gpioPortC
    error_on_duplicate: false

  SL_UARTDRV_EUSART_WS2812_UART_TX_PIN:
    type: config
    value: 2
    error_on_duplicate: false

  SL_UARTDRV_EUSART_WS2812_UART_RX_PORT:
    type: config
    value: gpioPortD
    error_on_duplicate: false

  SL_UARTDRV_EUSART_WS2812_UART_RX_PIN:
    type: config
    value: 2
    error_on_duplicate: false

  SL_I2CSPM_INST_PERIPHERAL: I2C0
  SL_I2CSPM_INST_SCL_PORT: gpioPortC
  SL_I2CSPM_INST_SCL_PIN: 6
  SL_I2CSPM_INST_SDA_PORT: gpioPortC
  SL_I2CSPM_INST_SDA_PIN: 7

  SL_SIMPLE_BUTTON_PIN_HOLE_BUTTON_PORT: gpioPortC
  SL_SIMPLE_BUTTON_PIN_HOLE_BUTTON_PIN: 5

  SL_APPLICATION_PRODUCT_ID: '{0xF4, 0x5E, 0x03, 0x17, 0xD5, 0x84, 0xAD, 0xA4, 0x7D, 0xDA, 0x6C, 0x95, 0x11, 0x2F, 0x24, 0xFA}'