name: SkyConnect Zigbee
device: EFR32MG21A020F512IM32
base_project: src/zigbee_ncp
filename: "{manifest_name}_{ezsp_version}"
sdk: "gecko_sdk:4.5.0"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: zigbee_ncp
  ezsp_version: dynamic
  baudrate: 115200

sdk_extension:
  - id: xncp
    vendor: nabucasa
    version: 1.0.0
  - id: xncp_common
    vendor: nabucasa
    version: 1.0.0

add_components:
- id: xncp_core
  vendor: nabucasa
  package: xncp
- id: xncp_common_commands
  vendor: nabucasa
  package: xncp_common

c_defines:
  XNCP_MFG_MANUF_NAME: '"Nabu Casa"'
  XNCP_MFG_BOARD_NAME: '"Home Assistant Connect ZBT-1"'
  XNCP_BUILD_STRING: template:"{now:%Y%m%d%H%M%S}"
  XNCP_MANUAL_SOURCE_ROUTE_TABLE_SIZE: 200

  EMBER_APS_UNICAST_MESSAGE_COUNT: 32
  EMBER_BINDING_TABLE_SIZE: 32
  EMBER_BROADCAST_TABLE_SIZE: 64
  EMBER_KEY_TABLE_SIZE: 12
  EMBER_MAX_END_DEVICE_CHILDREN: 32
  EMBER_PACKET_BUFFER_COUNT: 255
  EMBER_SOURCE_ROUTE_TABLE_SIZE: 200

  EMBER_CHILD_TABLE_SIZE:
    type: c_flag
    value: 32

  EMBER_ROUTE_TABLE_SIZE:
    type: c_flag
    value: 250

  SL_IOSTREAM_USART_VCOM_BAUDRATE: 115200
  SL_IOSTREAM_USART_VCOM_FLOW_CONTROL_TYPE: usartHwFlowControlCtsAndRts

  SL_IOSTREAM_USART_VCOM_PERIPHERAL: USART0
  SL_IOSTREAM_USART_VCOM_PERIPHERAL_NO: 0

  SL_IOSTREAM_USART_VCOM_TX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_TX_PIN:  6
  SL_IOSTREAM_USART_VCOM_RX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_RX_PIN:  5
  SL_IOSTREAM_USART_VCOM_CTS_PORT: gpioPortB
  SL_IOSTREAM_USART_VCOM_CTS_PIN:  1
  SL_IOSTREAM_USART_VCOM_RTS_PORT: gpioPortB
  SL_IOSTREAM_USART_VCOM_RTS_PIN:  0

  SL_IOSTREAM_USART_VCOM_RX_BUFFER_SIZE: 128

  SL_APPLICATION_PRODUCT_ID: '{0xE9, 0x92, 0x67, 0x94, 0xBB, 0x2C, 0x4E, 0xC8, 0x9F, 0x36, 0xD9, 0xC6, 0x79, 0x4A, 0x81, 0xFB}'
