name: ZB-GW04-1v1 Zigbee
device: EFR32MG21A020F768IM32
base_project: src/zigbee_ncp
filename: "{manifest_name}_{ezsp_version}_{fw_variant}_{baudrate}"
sdk: "simplicity_sdk:2024.6.2"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: zigbee_ncp
  ezsp_version: dynamic
  baudrate: 115200
  fw_variant: sw_flow

configuration:
  SL_ZIGBEE_CHILD_TABLE_SIZE: 32

c_defines:  
  SL_ZIGBEE_APS_UNICAST_MESSAGE_COUNT: 32
  SL_ZIGBEE_BINDING_TABLE_SIZE: 32
  SL_ZIGBEE_BROADCAST_TABLE_SIZE: 64
  SL_ZIGBEE_KEY_TABLE_SIZE: 12
  SL_ZIGBEE_MAX_END_DEVICE_CHILDREN: 32
  SL_ZIGBEE_SOURCE_ROUTE_TABLE_SIZE: 200

  SL_IOSTREAM_USART_VCOM_BAUDRATE: 115200
  SL_IOSTREAM_USART_VCOM_FLOW_CONTROL_TYPE: uartFlowControlSoftware
  SL_IOSTREAM_USART_VCOM_PERIPHERAL: USART0
  SL_IOSTREAM_USART_VCOM_PERIPHERAL_NO: 0

  SL_IOSTREAM_USART_VCOM_TX_PORT: gpioPortB
  SL_IOSTREAM_USART_VCOM_TX_PIN:  1

  SL_IOSTREAM_USART_VCOM_RX_PORT: gpioPortB
  SL_IOSTREAM_USART_VCOM_RX_PIN:  0

  SL_IOSTREAM_USART_VCOM_CTS_PORT: 0
  SL_IOSTREAM_USART_VCOM_CTS_PIN:  0

  SL_IOSTREAM_USART_VCOM_RTS_PORT: 0
  SL_IOSTREAM_USART_VCOM_RTS_PIN:  0

  SL_CLOCK_MANAGER_HFXO_CTUNE: 128

