name: Single firmware build

on:
  workflow_call:
    inputs:
      image_name:
        required: false
        type: string
        default: "ghcr.io/${{ github.repository_owner }}/silabs-firmware-builder:${{ inputs.sdk_version }}"
      firmware_name:
        required: true
        type: string
      project_file:
        required: true
        type: string
      project_name:
        required: true
        type: string
      baudrate:
        required: true
        type: number
      device:
        required: true
        type: string
      components:
        required: false
        type: string
      without_components:
        required: false
        type: string
      configuration:
        required: false
        type: string
      patchpath:
        required: false
        type: string
      sdkpatchpath:
        required: false
        type: string
      extra_c_defs:
        required: false
        type: string
      sdk_version:
        required: true
        type: string
      metadata_fw_type:
        required: true
        type: string
      metadata_extra:
        required: false
        default: "null"
        type: string
      slcp_yaml_changes:
        required: false
        type: string

jobs:
  firmware-build:
    name: Build firmware
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image_name }}
      options: --user root
    defaults:
      run:
        shell: su --shell=/bin/bash builder {0}
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Adjust permission
        shell: bash
        run: chown builder .

      - name: Link SDK extensions
        shell: bash
        run: |
          # XXX: slc-cli does not actually work when the extensions aren't in the SDK!
          ln -s $PWD/gecko_sdk_extensions /gecko_sdk/extension

      - name: Trust SDK extensions
        run: |
          for ext in /gecko_sdk/extension/*/; do
            slc signature trust --extension-path="$ext"
          done

      - name: Generate Firmware Project
        run: |
          slc generate \
              --with="${{ inputs.device }},${{ inputs.components }}" \
              --without="${{ inputs.without_components }}" \
              --project-file="${{ inputs.project_file }}" \
              --export-destination="$PWD/${{ inputs.firmware_name }}" \
              --copy-proj-sources --copy-sdk-sources --new-project --force \
              --configuration="${{ inputs.configuration }}"

      - name: Set Baudrate
        run: |
          cd ${{ inputs.firmware_name }}
          sed -Ei "s/^(\s*#define SL_\S+_VCOM_BAUDRATE\s+)[0-9]+/\\1${{ inputs.baudrate }}/" \
              config/sl_*usart_vcom_config.h

      - name: Patch Firmware
        if: "${{ inputs.patchpath != '' }}"
        run: |
          cd ${{ inputs.firmware_name }}
          for patch in "../${{ inputs.patchpath }}"/*.patch
          do
              echo "Applying ${patch}"
              patch -p1 < $patch
          done

      - name: Patch SDK
        if: "${{ inputs.sdkpatchpath != '' }}"
        run: |
          if [ ! -d "${{ inputs.sdkpatchpath }}" ]; then
              exit 0
          fi

          cd ${{ inputs.firmware_name }}/gecko_sdk_${{ inputs.sdk_version }}
          for patch in "../../${{ inputs.sdkpatchpath }}"/*.patch
          do
              echo "Applying ${patch}"
              patch -p1 < $patch
          done

      - name: Patch Makefile
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          LC_TIME=C meta_datetime=$(git log -1 --format="%cd" --date=format:"%b %-d %Y %H:%M:%S")
          cd ${{ inputs.firmware_name }}
          sed -i "s/^C_DEFS\s*=.*$/C_DEFS = '-DOPENTHREAD_BUILD_DATETIME=\"$meta_datetime\"' ${{ inputs.extra_c_defs }}/" \
            "${{ inputs.project_name }}.Makefile"

      - name: Patch SLCP project file
        if: "${{ inputs.slcp_yaml_changes != '' }}"
        run: |
          cd ${{ inputs.firmware_name }}
          yq --in-place --yaml-output '${{ inputs.slcp_yaml_changes }}' "${{ inputs.project_name }}.slcp"

      - name: Build Firmware
        run: |
          cd ${{ inputs.firmware_name }}
          make -f ${{ inputs.project_name }}.Makefile release
      - name: Add Firmware Metadata
        run: |
          cd ${{ inputs.firmware_name }}
          jq --null-input \
             '{
                "metadata_version": 1,
                "sdk_version": "${{ inputs.sdk_version }}",
                "fw_type": "${{ inputs.metadata_fw_type }}",
                "baudrate": ${{ inputs.baudrate }}
              } + ${{ inputs.metadata_extra }}' >  version.json

      - name: Generate gbl Firmware
        run: |
          cd ${{ inputs.firmware_name }}
          commander gbl create build/release/${{ inputs.project_name }}.gbl \
                    --app build/release/${{ inputs.project_name }}.out \
                    --device ${{ inputs.device }} --metadata version.json

      - name: Install node within container (act)
        if: ${{ env.ACT }}
        shell: bash
        run: |
            curl -fsSL https://deb.nodesource.com/nsolid_setup_deb.sh | bash -s 20
            apt-get install -y nodejs

      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: ${{ inputs.firmware_name }}
          path: ${{ inputs.firmware_name }}/build/release/*.*