name: Silicon Labs firmware build

on:
  workflow_call:
    inputs:
      firmware_name:
        required: true
        type: string
      project_file:
        required: true
        type: string
      project_name:
        required: true
        type: string
      device:
        required: true
        type: string
      components:
        required: false
        type: string
      configuration:
        required: false
        type: string
      patchpath:
        required: true
        type: string
      extra_c_defs:
        required: false
        type: string
      sdk_version:
        required: true
        type: string
      metadata_fw_type:
        required: true
        type: string
      metadata_extra:
        required: false
        default: "null"
        type: string

jobs:
  firmware-build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nabucasa/silabs-firmware-builder:${{ inputs.sdk_version }}
      options: --user root
    defaults:
      run:
        shell: su --shell=/bin/bash builder {0}
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Adjust permission
        shell: bash
        run: chown builder .
      - name: Generate Firmware Project
        run: |
          slc generate \
              --with="${{ inputs.device }},${{ inputs.components }}" \
              --project-file="${{ inputs.project_file }}" \
              --export-destination=${{ inputs.firmware_name }} \
              --copy-proj-sources --new-project --force \
              --configuration="${{ inputs.configuration }}"
      - name: Patch Firmware
        run: |
          cd ${{ inputs.firmware_name }}
          for patch in "../${{ inputs.patchpath }}"/*.patch
          do
              echo "Applying ${patch}"
              patch -p1 < $patch
          done

      - name: Build Firmware
        run: |
          cd ${{ inputs.firmware_name }}
          sed -i "s/^C_DEFS\s*=.*$/C_DEFS = ${{ inputs.extra_c_defs }}/" "${{ inputs.project_name }}.Makefile"
          make -f ${{ inputs.project_name }}.Makefile release
      - name: Add Firmware Metadata
        run: |
          cd ${{ inputs.firmware_name }}
          jq --null-input \
             --arg sdk_version "${{ inputs.sdk_version }}" \
             --argjson metadata_extra '${{ inputs.metadata_extra }}' \
             '{
                "metadata_version": 1,
                "sdk_version": $sdk_version,
                "fw_type": "${{ inputs.metadata_fw_type }}"
              } + $metadata_extra' >  version.json
      - name: Generate gbl Firmware
        run: |
          cd ${{ inputs.firmware_name }}
          commander gbl create build/release/${{ inputs.project_name }}.gbl \
                    --app build/release/${{ inputs.project_name }}.out \
                    --device ${{ inputs.device }} --metadata version.json

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.firmware_name }}
          path: ${{ inputs.firmware_name }}
